server:
  name: allthebest-service
  version: 1.0.0
  httpPort: 8811
  grpcPort: 8822
  host: 0.0.0.0

db:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: DB_PASS_ENV
  db_name: DemoDatabase
  minIdleConnections: 10
  maxOpenConnections: 30
  debugMode: false

jwt:
  duration_minutes: 15
  refresh_duration_minutes: 15
  signing_algorithm: HS256
  signing_key_env: SIGNING_KEY_ENV

log:
  enabled: true
  filename: allthebest.log
  logpath: ./

restApiOptions:
  address: http://127.0.0.1:8811
  timeout: 30
  debugMode: false
  withProxy: false
  skipTLS: true
  skipCheckRedirect: false

rpcOptions:
  address: 127.0.0.1:8822
  timeout: 30
